# Generated by Django 5.1.6 on 2026-03-13 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_studentnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturesession',
            name='session_type',
            field=models.CharField(choices=[('lecture', 'Lecture'), ('personal', 'Personal')], default='lecture', max_length=10),
        ),
    ]
